---
- hosts: all
  become: yes
  gather_facts: yes
  tasks:
  - name: in this task , i want install apache2 webserver on ubuntu 
    apt:
      name: apache2
      state: present
    when: ansible_os_family== "Debian"
  - name: in this task, i want to start webserver on ubuntu 
    service:
      name: apache2
      state: started
    when: ansible_os_family== "Debian"
